version: '3.9'

services:
  backend:
    build: .
    container_name: expenses-backend
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/expensesdb
      JWT_SECRET: mysecretkey
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16-alpine
    container_name: expenses-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expensesdb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
